### PR TITLE
Feature/snip1155

### PR DESCRIPTION
**Pull request by agent-mili**
Draft PR for snip1155 client implementation. Remains in draft mode till all tests are added.

### CODE REVIEW

**Review by Cashmaney — APPROVED** [review]

**Comment by Cashmaney** [comment]
I kind of want to add this. Still needs to be changed for secretjs 1.5, but if that's all that's missing (or there are a few tests that we need to finish up) we can fast-forward it and get it in the version before 1.5 starts seeing a lot of usage. Could be cool

**Comment by agent-mili** [comment]
Hi, there is a missing test for query "allBalances" . I'll add it in the next days and we can merge from my side.
I can do another PR for 1.5, but will take some time till I get there.

**Comment by agent-mili** [comment]
Hi, there is a missing test for query "allBalances" . I'll add it in the next days and we can merge from my side.
I can do another PR for 1.5, but will take some time till I get there.

**Comment by agent-mili** [comment]
merged master branch and looks good so far. But need to do a few adjustments in test file.

**Comment by agent-mili** [comment]
ready for 1.5

**Review by toml01 — COMMENTED** [review]
LGTM
@agent-mili could you add the code_hash param to all queries and txs in the tests so it won't spam the code_hash warning in CI?

**Comment by agent-mili** [comment]
> LGTM
> @agent-mili could you add the code_hash param to all queries and txs in the tests so it won't spam the code_hash warning in CI? (can't run CI for this PR for some reason btw)

yes I'll add code_hash.

**Review by toml01 — APPROVED** [review]

**Comment by toml01** [comment]
@agent-mili Looks good, can you please resolve the conflicts in `yarn.lock` so I can merge? You can do "accept all local" or something.
It's too much for the web editor, and I don't have permission to change your branch :)

**Comment by agent-mili** [comment]
merged  master into PR and choose master yarn.lock At the end I haven't installed any new packages.

**Comment by toml01** [comment]
Thank you ser

**Pull request merged**
